export default {
  // GET
  GET_EMPLOYEES: "GET_EMPLOYEES",

  // SET
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SET_LABOR_TYPES: "SET_LABOR_TYPES",
  SET_JOB_NUMBERS: "SET_JOB_NUMBERS",

  // CREATE
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  CREATE_LABOR_TYPE: "CREATE_LABOR_TYPE",
  CREATE_JOB_NUMBER: "CREATE_JOB_NUMBER",

  // UPDATE
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",

  // DELETE
  BULK_DELETE: "BULK_DELETE",

  CLOCK_IN: "CLOCK_IN",
  CLOCK_OUT: "CLOCK_OUT",
  GO_TO_LUNCH: "GO_TO_LUNCH",
  BACK_FROM_LUNCH: "BACK_FROM_LUNCH",

  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_LABOR_TYPE: "DELETE_LABOR_TYPE",
  DELETE_JOB_NUMBER: "DELETE_JOB_NUMBER",
  UPDATE_DELETIONS: "UPDATE_DELETIONS",
  RESET_DELETIONS: "RESET_DELETIONS",
  TOGGLE_TYPE: "TOGGLE_TYPE",

  TOGGLE_ADMIN_MODE: "TOGGLE_ADMIN_MODE",

  SELECT_EMPLOYEE: "SELECT_EMPLOYEE",
  SELECT_LABOR_TYPE: "SELECT_LABOR_TYPE",
  SELECT_JOB_NUMBER: "SELECT_JOB_NUMBER",
  SET_SELECTED: "SET_SELECTED",

  SET_ACTION_BUTTONS: "SET_ACTION_BUTTONS",

  OPEN_MESSAGE: "OPEN_MESSAGE",
  CLOSE_MESSAGE: "CLOSE_MESSAGE"

}
