// CREATE
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CREATE_LABOR_TYPE = "CREATE_LABOR_TYPE";
export const CREATE_JOB_NUMBER = "CREATE_JOB_NUMBER";

// READ
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_LABOR_TYPE = "GET_LABOR_TYPE";
export const GET_JOB_NUMBER = "GET_JOB_NUMBER";


// UPDATE
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_LABOR_TYPE = "UPDATE_LABOR_TYPE";
export const UPDATE_JOB_NUMBER = "UPDATE_JOB_NUMBER";
export const CLOCK_IN = "CLOCK_IN";
export const CLOCK_OUT = "CLOCK_OUT";
export const GO_TO_LUNCH = "GO_TO_LUNCH";
export const BACK_FROM_LUNCH = "BACK_FROM_LUNCH";

// DELETE
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_LABOR_TYPE = "DELETE_LABOR_TYPE";
export const DELETE_JOB_NUMBER = "DELETE_JOB_NUMBER";
export const BULK_DELETE = "BULK_DELETE";

// OTHER
export const UPDATE_DELETIONS = "UPDATE_DELETIONS";
export const TOGGLE_TYPE = "TOGGLE_TYPE";
