// CREATE
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CREATE_LABOR_TYPE = "CREATE_LABOR_TYPE";
export const CREATE_PROJECT_TYPE = "CREATE_PROJECT_TYPE";
export const CREATE_JOB_NUMBER = "CREATE_JOB_NUMBER";

// READ
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_LABOR_TYPE = "GET_LABOR_TYPE";
export const GET_PROJECT_TYPE = "GET_PROJECT_TYPE";
export const GET_JOB_NUMBER = "GET_JOB_NUMBER";


// UPDATE
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_LABOR_TYPE = "UPDATE_LABOR_TYPE";
export const UPDATE_PROJECT_TYPE = "UPDATE_PROJECT_TYPE";
export const UPDATE_JOB_NUMBER = "UPDATE_JOB_NUMBER";

// DELETE
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_LABOR_TYPE = "DELETE_LABOR_TYPE";
export const DELETE_PROJECT_TYPE = "DELETE_PROJECT_TYPE";
export const DELETE_JOB_NUMBER = "DELETE_JOB_NUMBER";
